name: 部署到 GitHub Pages

on:
  push:
    branches: [ translate/zh ]
  
  # 允许手动触发workflow
  workflow_dispatch:

# 设置GITHUB_TOKEN权限以允许部署到GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个并发部署，跳过正在运行的队列中的运行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: 设置 Node.js 环境
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: docs/yarn.lock
    
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libbz2-dev libffi-dev zlib1g-dev wget tar gzip rsync
    
    - name: 创建 Python 虚拟环境并安装依赖
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        python -m pip install --upgrade uv
        if [ -f docs/vercel_requirements.txt ]; then
          python -m uv pip install --pre -r docs/vercel_requirements.txt
        fi
        if [ -f scripts/partner_deps_list.py ] && [ -f docs/vercel_overrides.txt ]; then
          python -m uv pip install --pre $(python scripts/partner_deps_list.py) --overrides docs/vercel_overrides.txt
        fi
    
    - name: 运行构建脚本
      run: |
        source .venv/bin/activate
        cd docs
        # 使用 Makefile 中的 build 目标，跳过 vercel-deps
        make build
        make generate-references
        # 手动执行 vercel-build 的其余步骤
        rm -rf docs
        mv build/output-new/docs docs
        cp -r ../libs/cli/langchain_cli/integration_template src/theme
        rm -rf build
        mkdir -p static/api_reference
        git clone --depth=1 https://github.com/langchain-ai/langchain-api-docs-html.git
        mv langchain-api-docs-html/api_reference_build/html/* static/api_reference/
        rm -rf langchain-api-docs-html
        NODE_OPTIONS="--max-old-space-size=5000" yarn run docusaurus build
    
    - name: 设置 Pages
      uses: actions/configure-pages@v4
    
    - name: 上传构建产物
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 